### PR TITLE
Config without publishsettings

### PR DESCRIPTION
**Pull request by bear454**
re: better-initial-experience

A management cert allows the user to define the certificate used for API
authentication, instead of one generated by Azure (which is included in the
publishsettings file). Since no publishsettings file is available, the other
data normally supplied must be explicitly set in the config as well.

In order to accomplish this, use of publishsetting needed to be abstracted out of other classes, which necessitated a few other changes along the way.

### CODE REVIEW

**Comment by bear454** [comment]
@schaefi can you take a look at why Travis is failing? I get a clean test run locally:

```
$ make test
cd test/unit && py.test --no-cov-on-fail --cov=azurectl --cov-report=term-missing --cov-fail-under=100
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/jmason/projects/github/azurectl, inifile: setup.cfg
plugins: cov-2.2.1
collected 350 items 

account_service_test.py ............................
account_setup_test.py .......................
app_test.py .
cli_test.py ..........
commands_base_test.py .....
commands_compute_data-disk_test.py ...........
commands_compute_endpoint_test.py ...........
commands_compute_image_test.py ..............
commands_compute_request_test.py ...
commands_compute_reserved-ip_test.py .....
commands_compute_shell_test.py .
commands_compute_vm_test.py ......
commands_setup_account_test.py ............
commands_storage_account_test.py .........
commands_storage_container_test.py ............
commands_storage_disk_test.py .....
commands_storage_share_test.py ....
config_file_path_test.py .....
config_parser_test.py .....................
defaults_test.py .........
help_test.py ..
instance_cloud_service_test.py .............
instance_data_disk_test.py ............
instance_endpoint_test.py .........
instance_image_test.py ...........................
instance_reserved_ip_test.py ........
instance_virtual_machine_test.py .........
logger_test.py ...
management_request_result_test.py ....
storage_account_test.py ..............
storage_container_test.py .............
storage_fileshare_test.py ......
storage_page_blob_test.py ..........
storage_storage_test.py .......
utils_collector_test.py ..
utils_filetype_test.py ...
utils_output_test.py ...
utils_validations_test.py ....
utils_xz_test.py ......
------------------------------------------------------------- coverage: platform linux2, python 2.7.10-final-0 --------------------------------------------------------------
Name                                                                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------------------------------------------
/home/jmason/projects/github/azurectl/azurectl/__init__.py                           0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/account/__init__.py                   0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/account/service.py                  149      0   100%   
/home/jmason/projects/github/azurectl/azurectl/account/setup.py                    134      0   100%   
/home/jmason/projects/github/azurectl/azurectl/app.py                               13      0   100%   
/home/jmason/projects/github/azurectl/azurectl/azurectl_exceptions.py              181      0   100%   
/home/jmason/projects/github/azurectl/azurectl/cli.py                               67      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/__init__.py                  0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/base.py                     26      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_data-disk.py        55      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_endpoint.py         43      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_image.py            95      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_request.py          32      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_reserved-ip.py      42      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_shell.py            13      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/compute_vm.py               92      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/setup_account.py            98      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/storage_account.py          66      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/storage_container.py        79      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/storage_disk.py             55      0   100%   
/home/jmason/projects/github/azurectl/azurectl/commands/storage_share.py            40      0   100%   
/home/jmason/projects/github/azurectl/azurectl/config/__init__.py                    0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/config/file_path.py                  36      0   100%   
/home/jmason/projects/github/azurectl/azurectl/config/parser.py                    117      0   100%   
/home/jmason/projects/github/azurectl/azurectl/constants.py                          4      0   100%   
/home/jmason/projects/github/azurectl/azurectl/defaults.py                          40      0   100%   
/home/jmason/projects/github/azurectl/azurectl/help.py                               7      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/__init__.py                  0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/cloud_service.py            79      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/data_disk.py                58      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/endpoint.py                 61      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/image.py                   147      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/reserved_ip.py              35      0   100%   
/home/jmason/projects/github/azurectl/azurectl/instance/virtual_machine.py          75      0   100%   
/home/jmason/projects/github/azurectl/azurectl/logger.py                            35      0   100%   
/home/jmason/projects/github/azurectl/azurectl/management/__init__.py                0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/management/request_result.py         23      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/__init__.py                   0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/account.py                   68      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/container.py                 58      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/fileshare.py                 25      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/page_blob.py                 51      0   100%   
/home/jmason/projects/github/azurectl/azurectl/storage/storage.py                   59      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/__init__.py                     0      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/collector.py                    7      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/filetype.py                    18      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/output.py                      30      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/validations.py                 10      0   100%   
/home/jmason/projects/github/azurectl/azurectl/utils/xz.py                          48      0   100%   
/home/jmason/projects/github/azurectl/azurectl/version.py                            2      0   100%   
--------------------------------------------------------------------------------------------------------------
TOTAL                                                                             2373      0   100%   

======================================================================== 350 passed in 10.97 seconds ========================================================================
```

**Comment by schaefi** [comment]
your tree is broken. In your branch I could not find the source files

* management/data_disk.py
* management/endpoint.py
* management/reserved_ip.py
* management/service_manager.py

maybe more is broken.

The good test result is most probably only because you have a binary variant of these files "*.pyc"
in your tree

You can reproduce the problem if you delete all *.pyc's and run the tests again

So something is broken in your source tree, master is clean I have checked that

**Comment by bear454** [comment]
Thanks @schaefi - I see them now.

**Comment by bear454** [comment]
git push --force

**Comment by schaefi** [comment]
yeah great work :+1: :+1:

**Pull request merged**
