### PR TITLE
Fix issue #24

### PR DESCRIPTION
**Pull request by rjschwei**

### CODE REVIEW

**Comment by schaefi** [comment]
In principal I don't have a strong opinion on this, but there is one thing which bothers me with version names in source tarball. Any time you submit a new package you have to osc delete the old source and osc add the new one. I find it pretty nice if I don't have to care for these kind of name change at all and just copy the new sources over the old ones and submit the thing

**Comment by schaefi** [comment]
a short look into the spec file outlines the versions too and I'm mostly interested in the version when I need to debug a customer problem which requires me to ask for rpm -q or azurectl --version anyways

**Comment by rjschwei** [comment]
If the tarball i snot versioned there is nothing to, at a quick glance, confirm consistency. I can set the sec file version to 1.0 and still have the tarball version from 0.9 simply because I forgot to copy the newly downloaded 1.0 tarball into the package. Versioning the tarball provides a little extra "protection" from silly mistakes.

**Comment by schaefi** [comment]
ok

**Pull request merged**
