### PR TITLE
Short switch `-v` for version.

### PR DESCRIPTION
**Pull request by bear454**

### CODE REVIEW

**Comment by schaefi** [comment]
Thanks, I have tested the completion generator with this change and unfortunately it broke. I'm going to fix the completion generator first and will then merge this commit

**Comment by schaefi** [comment]
done now, merging

**Comment by bear454** [comment]
Sorry about the completion generation - maybe we can automate testing that? ;-)

**Comment by schaefi** [comment]
>    Sorry about the completion generation - maybe we can automate testing
>    that? ;-)

also thought about it but it's pretty hard to test bash code and I'm not aware of any completion automation which provides me a good return result for a test. I think it would be possible if we rewrite the completion python code which creates the bash sequences to be testable. But that would be a not so small side project which I would consider not a prio at the moment

**Pull request merged**
