### PR TITLE
Adaptions to replication/publishing SDK patches

### PR DESCRIPTION
**Pull request by schaefi**
My patches to the Azure SDK were accepted, however I had to rename the methods and the class where they live after review by $MS. Thus these changes have an effect on azurectl too

### CODE REVIEW

**Comment by schaefi** [comment]
Please no merge until the following PR was accepted by $MS

https://github.com/Azure/azure-sdk-for-python/pull/497

**Comment by bear454** [comment]
@schaefi , do we need to wait for the API pull request before merging this in?

**Comment by schaefi** [comment]
no we don't have to wait, we can merge this in as soon as we are ok with it

However the package release is kind of blocked until $MS has merged my PR. The next package release should also care for a version dependency on the sdk. That's because we have released the sdk with my patches but $MS wants my code to live in a another namespace which is an incompatible
change.

I'll care for this when I submit new packages

**Comment by schaefi** [comment]
yay patches merged to the microsoft azure sdk :)

**Comment by schaefi** [comment]
ok to merge this ? I need a thumbs up :)

**Comment by bear454** [comment]
Yes, merge it!

James Mason
Technical Architect, Public Cloud
openSUSE Member
SUSE
jmason@suse.com

**Pull request merged**
