### PR TITLE
Update code base to use SDK's dev branch

### PR DESCRIPTION
**Pull request by schaefi**
Microsoft will release the dev branch to be the new SDK in August. The version will be at 0.20.x and is incompatible to 0.11.x I have ported the files api support to the dev branch and also updated azurectl to work with the latest dev branch

### CODE REVIEW

**Comment by schaefi** [comment]
I had a good discussion with $MS on the development branch side of things. As you can see with this pull request I'm up and running with the dev branch they will release in August.

Along with this change I suggest we also rebuild our python-azure-sdk rpm package to use the latest dev branch.

I'm confident that my new files pull request will make it into the dev branch

**Comment by schaefi** [comment]
According to $MS plans we should wait with our azurectl submission until August when they release 0.20.x of the SDK. imho this gives us also some time to add support for the publish and replication api

**Comment by schaefi** [comment]
For testing I have build python-azure-sdk 0.20.x in Cloud:Tools

**Comment by rjschwei** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 07/23/2015 10:32 AM, Marcus Schäfer wrote:
> Merged #39.

This was pre-mature IMHO, now we end up using an SDK that is according
to the upstream project unstable with additional API changes to come.
I would have much rather waited until 0.20.x was actually released. It
is getting harder to contribute to azurectl and the SDK by the minute :(




- -- 
Robert Schweikert                   MAY THE SOURCE BE WITH YOU
Public Cloud Architect                         LINUX
rjschwei@suse.com
IRC: robjo
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBAgAGBQJVtnEHAAoJEE4FgL32d2UkBqYIAIl8PMdhvRHuU8cYLHDUTh3W
rtjUrvaxhhkRNykQMNGzai/Qj0TEQ7jeFmC70W+QTuTRy7D0n23/ppmKkdhXaD1j
6MQnodNqXf5/POGS0VnU2jwK0NKDe4x3e0AdSQ4+DEPysNwX/+8Jgvz7Lrg2j5OW
51Do9VgvfRDkULxJoh5PtdG0hFWTYrapAA7jvanUZauG6B6aZuuu1xDse2CRzZBN
PUlA6kcbxp3cidm14LoveTepHzIR2m5UqlmQs4cCS3L4OLbtv5ySo2Mt8afy/y32
uksDuMgd7CnnAWp5zvGM1P3wow4cdP82MuTRicFWmEg0iT0tyPHJVmiKxEqvIEw=
=kH/i
-----END PGP SIGNATURE-----

**Comment by schaefi** [comment]
>    This was pre-mature IMHO, now we end up using an SDK that is according
>    to the upstream project unstable with additional API changes to come.

There is no other way if we want to continue developing azurectl with
support for file shares, publishing and replication. They will
not accept any patches to the stable branch

>    I would have much rather waited until 0.20.x was actually released. It
>    is getting harder to contribute to azurectl and the SDK by the minute
>    :(

There is no problem, our code is covered 100% by tests, any incompatible
change in the api is immediately recognized and we can follow their
development which we have to until they release.

The release will happen in August, this is not so far away and I want
to have an azurectl version working from day one once they will release

I agree we will not promote azurectl or put it into sles until they
have released the dev branch to be the new sdk

Support for file shares is in now in, thus I already could get rid of one
patch we carry around. For me personally things became easier as before
because I can follow their work

Bunch of the SDK code will also be autogenerated in the future.
I also discussed with them that the new sdk is incompatible to 0.11
in namespace and other parts. They know that this is a break but
due to their internal restructuring process (storage handled by another team)
they don't see another way

For me there is no other way as following their style and sticking to
the current master branch is a waste of time, nothing will work once
they do the switch.

Instead of dealing with tons of problems I wanted to be there in time
Actually I'm quite happy that I got it all running including file share
support in the sdk and not as a suse patch

It's a pity that you think differently

**Pull request merged**
